# Generated by Django 6.0.2 on 2026-02-15 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utangerapp', '0002_utangsbyuser_utangstouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='utangsbyuser',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utangstouser',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utangstouser',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=128),
            preserve_default=False,
        ),
    ]
