# Generated by Django 6.0.2 on 2026-02-15 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utangerapp', '0003_utangsbyuser_date_utangstouser_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utangstouser',
            name='users_utangs_to_users',
        ),
        migrations.CreateModel(
            name='Utang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=128)),
                ('date', models.DateField(auto_now_add=True)),
                ('isUtangToUser', models.BooleanField(default=True)),
                ('utangs', models.ManyToManyField(related_name='utangs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UtangsByUser',
        ),
        migrations.DeleteModel(
            name='UtangsToUser',
        ),
    ]
