# Generated by Django 6.0.2 on 2026-02-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utangerapp', '0004_remove_utangstouser_users_utangs_to_users_utang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utang',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
